export const EQUIPMENT = ['Barbell', 'Dumbbell', 'Kettlebell', 'Machine', 'Cable', 'Bodyweight', 'Other']

export const DEFAULT_EXERCISES = [
  { id: "ex_goblet_squat", name: "Goblet Squats", equipment: "Kettlebell", muscles: ["Quads","Glutes","Core"] },
  { id: "ex_trapbar_dl", name: "Trap Bar Deadlift", equipment: "Barbell", muscles: ["Hamstrings","Glutes","Back"] },
  { id: "ex_db_rev_lunge", name: "Dumbbell Reverse Lunges", equipment: "Dumbbell", muscles: ["Quads","Glutes"] },
  { id: "ex_pallof", name: "Pallof Press", equipment: "Cable", muscles: ["Core","Shoulders"] },
  { id: "ex_ng_db_press", name: "Neutral Grip Dumbbell Press", equipment: "Dumbbell", muscles: ["Chest","Shoulders","Triceps"] },
  { id: "ex_bent_row", name: "Bent-Over Dumbbell Rows", equipment: "Dumbbell", muscles: ["Back","Biceps"] },
  { id: "ex_hk_ohp", name: "Half-Kneeling Overhead Press", equipment: "Dumbbell", muscles: ["Core","Shoulders","Triceps"] },
  { id: "ex_weighted_pullup", name: "Weighted Pull-ups", equipment: "Bodyweight", muscles: ["Back","Biceps"] },
  { id: "ex_kb_swing", name: "Kettlebell Swings", equipment: "Kettlebell", muscles: ["Hamstrings","Glutes","Core"] },
  { id: "ex_weighted_pushup", name: "Weighted Push-ups", equipment: "Bodyweight", muscles: ["Chest","Shoulders","Triceps"] },
  { id: "ex_bulg_split", name: "Bulgarian Split Squats", equipment: "Dumbbell", muscles: ["Quads","Glutes"] },
  { id: "ex_renegade_row", name: "Renegade Rows", equipment: "Dumbbell", muscles: ["Core","Back","Shoulders"] },
  { id: "ex_front_squat", name: "Front Squats", equipment: "Barbell", muscles: ["Quads","Core"] },
  { id: "ex_leg_press", name: "Leg Press", equipment: "Machine", muscles: ["Quads","Glutes"] },
  { id: "ex_walking_lunge", name: "Walking Lunges", equipment: "Dumbbell", muscles: ["Quads","Glutes"] },
  { id: "ex_hip_thrust", name: "Hip Thrusts", equipment: "Barbell", muscles: ["Hamstrings","Glutes"] },
  { id: "ex_rdl", name: "Romanian Deadlift", equipment: "Barbell", muscles: ["Hamstrings","Glutes"] },
  { id: "ex_step_up", name: "Step-ups", equipment: "Dumbbell", muscles: ["Quads","Glutes"] },
  { id: "ex_lat_pulldown", name: "Lat Pulldown", equipment: "Cable", muscles: ["Back","Biceps"] },
  { id: "ex_single_row", name: "Single-Arm Row", equipment: "Dumbbell", muscles: ["Back","Biceps"] },
  { id: "ex_seated_cable_row", name: "Seated Cable Row", equipment: "Cable", muscles: ["Back","Biceps"] },
  { id: "ex_incline_press", name: "Incline DB Press", equipment: "Dumbbell", muscles: ["Chest","Shoulders","Triceps"] },
  { id: "ex_flat_bench", name: "Flat Bench Press", equipment: "Barbell", muscles: ["Chest","Shoulders","Triceps"] },
  { id: "ex_chest_fly", name: "Chest Fly", equipment: "Dumbbell", muscles: ["Chest"] },
  { id: "ex_arnold_press", name: "Arnold Press", equipment: "Dumbbell", muscles: ["Shoulders","Triceps"] },
  { id: "ex_lateral_raise", name: "Lateral Raises", equipment: "Dumbbell", muscles: ["Shoulders"] },
  { id: "ex_face_pull", name: "Face Pulls", equipment: "Cable", muscles: ["Back","Shoulders"] },
  { id: "ex_plank", name: "Plank", equipment: "Bodyweight", muscles: ["Core"] },
  { id: "ex_dead_bug", name: "Dead Bug", equipment: "Bodyweight", muscles: ["Core"] },
  { id: "ex_russian_twist", name: "Russian Twists", equipment: "Bodyweight", muscles: ["Core"] },
  { id: "ex_nordic_curl", name: "Nordic Curls", equipment: "Bodyweight", muscles: ["Hamstrings"] },
  { id: "ex_leg_curl", name: "Leg Curls", equipment: "Machine", muscles: ["Hamstrings"] },
  { id: "ex_good_morning", name: "Good Mornings", equipment: "Barbell", muscles: ["Hamstrings","Glutes"] },
  { id: "ex_tricep_dip", name: "Tricep Dips", equipment: "Bodyweight", muscles: ["Chest","Triceps"] },
  { id: "ex_oh_tricep_ext", name: "Overhead Tricep Extension", equipment: "Dumbbell", muscles: ["Triceps"] },
  { id: "ex_hammer_curl", name: "Hammer Curls", equipment: "Dumbbell", muscles: ["Biceps"] },
  { id: "ex_concentration_curl", name: "Concentration Curls", equipment: "Dumbbell", muscles: ["Biceps"] },
  { id: "ex_chinup", name: "Chin-ups", equipment: "Bodyweight", muscles: ["Back","Biceps"] },
  { id: "ex_calf_raise", name: "Calf Raises", equipment: "Bodyweight", muscles: ["Calves"] },
  { id: "ex_leg_extensions", name: "Leg Extensions", equipment: "Machine", muscles: ["Quads"] },
  { id: "ex_sissy_squats", name: "Sissy Squats", equipment: "Bodyweight", muscles: ["Quads"] },
  { id: "ex_hack_squats", name: "Hack Squats", equipment: "Machine", muscles: ["Quads","Glutes"] },
  { id: "ex_box_squats", name: "Box Squats", equipment: "Barbell", muscles: ["Quads","Hamstrings","Glutes"] },
  { id: "ex_sumo_deadlift", name: "Sumo Deadlift", equipment: "Barbell", muscles: ["Quads","Hamstrings","Glutes","Back"] },
  { id: "ex_glute_bridges", name: "Glute Bridges", equipment: "Bodyweight", muscles: ["Hamstrings","Glutes"] },
  { id: "ex_cable_pull_throughs", name: "Cable Pull-Throughs", equipment: "Cable", muscles: ["Hamstrings","Glutes"] },
  { id: "ex_seated_calf_raises", name: "Seated Calf Raises", equipment: "Machine", muscles: ["Calves"] },
  { id: "ex_standing_barbell_calf_raises", name: "Standing Barbell Calf Raises", equipment: "Barbell", muscles: ["Calves"] },
  { id: "ex_donkey_calf_raises", name: "Donkey Calf Raises", equipment: "Machine", muscles: ["Calves"] },
  { id: "ex_decline_bench_press", name: "Decline Bench Press", equipment: "Barbell", muscles: ["Chest","Shoulders","Triceps"] },
  { id: "ex_close_grip_bench_press", name: "Close-Grip Bench Press", equipment: "Barbell", muscles: ["Chest","Shoulders","Triceps"] },
  { id: "ex_cable_crossover", name: "Cable Crossover", equipment: "Cable", muscles: ["Chest"] },
  { id: "ex_pec_deck_fly", name: "Pec Deck Fly", equipment: "Machine", muscles: ["Chest"] },
  { id: "ex_push_press", name: "Push Press", equipment: "Barbell", muscles: ["Quads","Shoulders","Triceps"] },
  { id: "ex_upright_rows", name: "Upright Rows", equipment: "Barbell", muscles: ["Back","Shoulders"] },
  { id: "ex_front_raises", name: "Front Raises", equipment: "Dumbbell", muscles: ["Shoulders"] },
  { id: "ex_reverse_pec_deck", name: "Reverse Pec Deck", equipment: "Machine", muscles: ["Back","Shoulders"] },
  { id: "ex_cable_lateral_raises", name: "Cable Lateral Raises", equipment: "Cable", muscles: ["Shoulders"] },
  { id: "ex_shrugs", name: "Shrugs", equipment: "Dumbbell", muscles: ["Back","Shoulders"] },
  { id: "ex_t_bar_rows", name: "T-Bar Rows", equipment: "Barbell", muscles: ["Back","Biceps"] },
  { id: "ex_pendlay_rows", name: "Pendlay Rows", equipment: "Barbell", muscles: ["Back","Biceps"] },
  { id: "ex_chest_supported_rows", name: "Chest-Supported Rows", equipment: "Dumbbell", muscles: ["Back","Biceps"] },
  { id: "ex_straight_arm_pulldown", name: "Straight-Arm Pulldown", equipment: "Cable", muscles: ["Back"] },
  { id: "ex_dumbbell_pullover", name: "Dumbbell Pullover", equipment: "Dumbbell", muscles: ["Chest","Back"] },
  { id: "ex_kroc_rows", name: "Kroc Rows", equipment: "Dumbbell", muscles: ["Back","Biceps"] },
  { id: "ex_skullcrushers", name: "Skullcrushers", equipment: "Barbell", muscles: ["Triceps"] },
  { id: "ex_tricep_pushdowns", name: "Tricep Pushdowns", equipment: "Cable", muscles: ["Triceps"] },
  { id: "ex_rope_tricep_extensions", name: "Rope Tricep Extensions", equipment: "Cable", muscles: ["Triceps"] },
  { id: "ex_jm_press", name: "JM Press", equipment: "Barbell", muscles: ["Chest","Triceps"] },
  { id: "ex_preacher_curls", name: "Preacher Curls", equipment: "Barbell", muscles: ["Biceps"] },
  { id: "ex_ez_bar_curls", name: "EZ-Bar Curls", equipment: "Barbell", muscles: ["Biceps"] },
  { id: "ex_cable_curls", name: "Cable Curls", equipment: "Cable", muscles: ["Biceps"] },
  { id: "ex_spider_curls", name: "Spider Curls", equipment: "Dumbbell", muscles: ["Biceps"] },
  { id: "ex_reverse_curls", name: "Reverse Curls", equipment: "Barbell", muscles: ["Biceps"] },
  { id: "ex_zottman_curls", name: "Zottman Curls", equipment: "Dumbbell", muscles: ["Biceps"] },
  { id: "ex_ab_wheel_rollout", name: "Ab Wheel Rollout", equipment: "Other", muscles: ["Core"] },
  { id: "ex_hanging_leg_raises", name: "Hanging Leg Raises", equipment: "Bodyweight", muscles: ["Core"] },
  { id: "ex_cable_crunches", name: "Cable Crunches", equipment: "Cable", muscles: ["Core"] },
  { id: "ex_v_ups", name: "V-Ups", equipment: "Bodyweight", muscles: ["Core"] },
  { id: "ex_bicycle_crunches", name: "Bicycle Crunches", equipment: "Bodyweight", muscles: ["Core"] },
  { id: "ex_woodchoppers", name: "Woodchoppers", equipment: "Cable", muscles: ["Core"] },
  { id: "ex_l_sit", name: "L-Sit", equipment: "Bodyweight", muscles: ["Core","Triceps"] },
  { id: "ex_hollow_body_hold", name: "Hollow Body Hold", equipment: "Bodyweight", muscles: ["Core"] },
  { id: "ex_decline_crunches", name: "Decline Crunches", equipment: "Bodyweight", muscles: ["Core"] },
  { id: "ex_farmer_s_walk", name: "Farmer's Walk", equipment: "Dumbbell", muscles: ["Core","Back"] },
  { id: "ex_suitcase_carry", name: "Suitcase Carry", equipment: "Kettlebell", muscles: ["Core"] },
  { id: "ex_landmine_press", name: "Landmine Press", equipment: "Barbell", muscles: ["Chest","Shoulders","Triceps"] },
  { id: "ex_landmine_180s", name: "Landmine 180s", equipment: "Barbell", muscles: ["Core"] },
  { id: "ex_z_press", name: "Z Press", equipment: "Dumbbell", muscles: ["Core","Shoulders","Triceps"] },
  { id: "ex_pistol_squats", name: "Pistol Squats", equipment: "Bodyweight", muscles: ["Quads","Glutes","Core"] },
  { id: "ex_cossack_squats", name: "Cossack Squats", equipment: "Bodyweight", muscles: ["Quads","Glutes"] },
  { id: "ex_reverse_hyperextensions", name: "Reverse Hyperextensions", equipment: "Machine", muscles: ["Hamstrings","Glutes","Back"] },
  { id: "ex_back_extensions", name: "Back Extensions", equipment: "Machine", muscles: ["Hamstrings","Glutes","Back"] },
  { id: "ex_rack_pulls", name: "Rack Pulls", equipment: "Barbell", muscles: ["Hamstrings","Glutes","Back"] },
  { id: "ex_seal_rows", name: "Seal Rows", equipment: "Barbell", muscles: ["Back","Biceps"] },
  { id: "ex_bear_crawls", name: "Bear Crawls", equipment: "Bodyweight", muscles: ["Quads","Core","Shoulders"] },
  { id: "ex_turkish_get_ups", name: "Turkish Get-Ups", equipment: "Kettlebell", muscles: ["Core","Shoulders"] },
  { id: "ex_single_leg_rdl", name: "Single-Leg RDL", equipment: "Dumbbell", muscles: ["Hamstrings","Glutes","Core"] },
  { id: "ex_deficit_deadlift", name: "Deficit Deadlift", equipment: "Barbell", muscles: ["Quads","Hamstrings","Glutes","Back"] },
  { id: "ex_deficit_push_ups", name: "Deficit Push-ups", equipment: "Bodyweight", muscles: ["Chest","Shoulders","Triceps"] },
  { id: "ex_wall_sit", name: "Wall Sit", equipment: "Bodyweight", muscles: ["Quads","Glutes"] },
  { id: "ex_jump_squats", name: "Jump Squats", equipment: "Bodyweight", muscles: ["Quads","Glutes"] },
  { id: "ex_lunge_jumps", name: "Lunge Jumps", equipment: "Bodyweight", muscles: ["Quads","Glutes"] },
  { id: "ex_curtsy_lunges", name: "Curtsy Lunges", equipment: "Bodyweight", muscles: ["Quads","Glutes"] },
  { id: "ex_hack_squat_machine", name: "Hack Squat Machine", equipment: "Machine", muscles: ["Quads","Glutes"] },
  { id: "ex_lying_leg_curls", name: "Lying Leg Curls", equipment: "Machine", muscles: ["Hamstrings"] },
  { id: "ex_seated_leg_curls", name: "Seated Leg Curls", equipment: "Machine", muscles: ["Hamstrings"] },
  { id: "ex_stiff_legged_deadlift", name: "Stiff-Legged Deadlift", equipment: "Barbell", muscles: ["Hamstrings","Glutes","Back"] },
  { id: "ex_reverse_lunge_to_knee_drive", name: "Reverse Lunge to Knee Drive", equipment: "Bodyweight", muscles: ["Quads","Glutes","Core"] },
  { id: "ex_frog_pumps", name: "Frog Pumps", equipment: "Bodyweight", muscles: ["Glutes"] },
  { id: "ex_clamshells", name: "Clamshells", equipment: "Bodyweight", muscles: ["Glutes"] },
  { id: "ex_fire_hydrants", name: "Fire Hydrants", equipment: "Bodyweight", muscles: ["Glutes","Core"] },
  { id: "ex_bird_dog", name: "Bird Dog", equipment: "Bodyweight", muscles: ["Glutes","Core","Back"] },
  { id: "ex_superman", name: "Superman", equipment: "Bodyweight", muscles: ["Glutes","Core","Back"] },
  { id: "ex_flutter_kicks", name: "Flutter Kicks", equipment: "Bodyweight", muscles: ["Core"] },
  { id: "ex_scissor_kicks", name: "Scissor Kicks", equipment: "Bodyweight", muscles: ["Core"] },
  { id: "ex_leg_raises", name: "Leg Raises", equipment: "Bodyweight", muscles: ["Core"] },
  { id: "ex_mountain_climbers", name: "Mountain Climbers", equipment: "Bodyweight", muscles: ["Core","Shoulders"] },
  { id: "ex_spiderman_push_ups", name: "Spiderman Push-ups", equipment: "Bodyweight", muscles: ["Core","Chest","Triceps"] },
  { id: "ex_diamond_push_ups", name: "Diamond Push-ups", equipment: "Bodyweight", muscles: ["Chest","Shoulders","Triceps"] },
  { id: "ex_archer_push_ups", name: "Archer Push-ups", equipment: "Bodyweight", muscles: ["Chest","Shoulders","Triceps"] },
  { id: "ex_pike_push_ups", name: "Pike Push-ups", equipment: "Bodyweight", muscles: ["Shoulders","Triceps"] },
  { id: "ex_handstand_push_ups", name: "Handstand Push-ups", equipment: "Bodyweight", muscles: ["Core","Shoulders","Triceps"] },
  { id: "ex_guillotine_press", name: "Guillotine Press", equipment: "Barbell", muscles: ["Chest","Shoulders","Triceps"] },
  { id: "ex_svend_press", name: "Svend Press", equipment: "Other", muscles: ["Chest","Shoulders"] },
  { id: "ex_dumbbell_flyes", name: "Dumbbell Flyes", equipment: "Dumbbell", muscles: ["Chest"] },
  { id: "ex_machine_flyes", name: "Machine Flyes", equipment: "Machine", muscles: ["Chest"] },
  { id: "ex_reverse_grip_bench_press", name: "Reverse Grip Bench Press", equipment: "Barbell", muscles: ["Chest","Triceps"] },
  { id: "ex_incline_cable_flyes", name: "Incline Cable Flyes", equipment: "Cable", muscles: ["Chest"] },
  { id: "ex_decline_cable_flyes", name: "Decline Cable Flyes", equipment: "Cable", muscles: ["Chest"] },
  { id: "ex_meadow_rows", name: "Meadow Rows", equipment: "Barbell", muscles: ["Back","Biceps"] },
  { id: "ex_inverted_rows", name: "Inverted Rows", equipment: "Bodyweight", muscles: ["Core","Back","Biceps"] },
  { id: "ex_rack_chins", name: "Rack Chins", equipment: "Bodyweight", muscles: ["Back","Biceps"] },
  { id: "ex_v_bar_pulldown", name: "V-Bar Pulldown", equipment: "Cable", muscles: ["Back","Biceps"] },
  { id: "ex_underhand_pulldown", name: "Underhand Pulldown", equipment: "Cable", muscles: ["Back","Biceps"] },
  { id: "ex_dumbbell_shrugs", name: "Dumbbell Shrugs", equipment: "Dumbbell", muscles: ["Back","Shoulders"] },
  { id: "ex_barbell_shrugs", name: "Barbell Shrugs", equipment: "Barbell", muscles: ["Back","Shoulders"] },
  { id: "ex_bradford_press", name: "Bradford Press", equipment: "Barbell", muscles: ["Shoulders","Triceps"] },
  { id: "ex_cuban_press", name: "Cuban Press", equipment: "Dumbbell", muscles: ["Shoulders"] },
  { id: "ex_y_raises", name: "Y-Raises", equipment: "Dumbbell", muscles: ["Back","Shoulders"] },
  { id: "ex_tate_press", name: "Tate Press", equipment: "Dumbbell", muscles: ["Triceps"] },
  { id: "ex_kickbacks", name: "Kickbacks", equipment: "Dumbbell", muscles: ["Triceps"] },
  { id: "ex_drag_curls", name: "Drag Curls", equipment: "Barbell", muscles: ["Biceps"] },
  { id: "ex_waiter_curls", name: "Waiter Curls", equipment: "Dumbbell", muscles: ["Biceps"] },
  { id: "ex_incline_dumbbell_curls", name: "Incline Dumbbell Curls", equipment: "Dumbbell", muscles: ["Biceps"] },
  { id: "ex_tibialis_raises", name: "Tibialis Raises", equipment: "Bodyweight", muscles: ["Calves"] },
  { id: "ex_zercher_squats", name: "Zercher Squats", equipment: "Barbell", muscles: ["Quads","Glutes","Core"] },
  { id: "ex_machine_shoulder_press", name: "Machine Shoulder Press", equipment: "Machine", muscles: ["Shoulders","Triceps"] },
  { id: "ex_hip_abductions", name: "Hip Abductions", equipment: "Machine", muscles: ["Glutes"] },
  { id: "ex_hip_adductions", name: "Hip Adductions", equipment: "Machine", muscles: ["Quads"] },
  { id: "ex_db_ohp", name: "Dumbbell Overhead Press", equipment: "Dumbbell", muscles: ["Shoulders","Triceps"] },
  { id: "ex_db_curl", name: "Dumbbell Bicep Curls", equipment: "Dumbbell", muscles: ["Biceps"] },
  { id: "ex_side_plank", name: "Side Plank", equipment: "Bodyweight", muscles: ["Core"] },
  { id: "ex_bw_squat", name: "Bodyweight Squats", equipment: "Bodyweight", muscles: ["Quads","Glutes"] },
  { id: "ex_bw_rev_lunge", name: "Bodyweight Reverse Lunges", equipment: "Bodyweight", muscles: ["Quads","Glutes"] },
  { id: "ex_pushup", name: "Push-ups", equipment: "Bodyweight", muscles: ["Chest","Triceps","Shoulders"] },
  { id: "ex_machine_chest_press", name: "Machine Chest Press", equipment: "Machine", muscles: ["Chest","Triceps","Shoulders"] },
]

export const exById = (list, id) => list.find((e) => e.id === id)

/**
 * Provided training templates (from the user's coaching plan docs).
 * Template exercise shape: { exerciseId, targetSets, reps, rest }
 * `reps` is the low end of the doc's rep range; `rest` is in seconds.
 */
export function makeDefaultTemplates() {
  return [
    {
      id: 'tmpl_upper_day',
      name: 'Upper Day',
      exercises: [
        { exerciseId: 'ex_db_ohp',        targetSets: 3, reps: 8,  rest: 90 },
        { exerciseId: 'ex_bent_row',      targetSets: 3, reps: 10, rest: 90 },
        { exerciseId: 'ex_db_curl',       targetSets: 3, reps: 10, rest: 60 },
        { exerciseId: 'ex_oh_tricep_ext', targetSets: 3, reps: 10, rest: 60 },
        { exerciseId: 'ex_lateral_raise', targetSets: 3, reps: 12, rest: 45 },
        { exerciseId: 'ex_shrugs',        targetSets: 2, reps: 12, rest: 45 },
        { exerciseId: 'ex_plank',         targetSets: 3, reps: 45, rest: 45 },
      ],
    },
    {
      id: 'tmpl_lower_day',
      name: 'Lower Day',
      exercises: [
        { exerciseId: 'ex_goblet_squat',  targetSets: 3, reps: 8,  rest: 120 },
        { exerciseId: 'ex_glute_bridges', targetSets: 3, reps: 10, rest: 90 },
        { exerciseId: 'ex_db_rev_lunge',  targetSets: 3, reps: 10, rest: 90 },
        { exerciseId: 'ex_calf_raise',    targetSets: 3, reps: 15, rest: 45 },
        { exerciseId: 'ex_dead_bug',      targetSets: 3, reps: 10, rest: 45 },
        { exerciseId: 'ex_side_plank',    targetSets: 3, reps: 45, rest: 45 },
      ],
    },
    {
      id: 'tmpl_bodyweight_day',
      name: 'Bodyweight-Only Day',
      exercises: [
        { exerciseId: 'ex_bw_squat',      targetSets: 3, reps: 20, rest: 60 },
        { exerciseId: 'ex_bw_rev_lunge',  targetSets: 3, reps: 12, rest: 60 },
        { exerciseId: 'ex_glute_bridges', targetSets: 3, reps: 15, rest: 45 },
        { exerciseId: 'ex_pushup',        targetSets: 3, reps: 12, rest: 60 },
        { exerciseId: 'ex_pike_push_ups', targetSets: 2, reps: 8,  rest: 60 },
        { exerciseId: 'ex_plank',         targetSets: 3, reps: 45, rest: 45 },
        { exerciseId: 'ex_dead_bug',      targetSets: 3, reps: 12, rest: 30 },
        { exerciseId: 'ex_calf_raise',    targetSets: 3, reps: 25, rest: 30 },
      ],
    },
    {
      id: 'tmpl_upper_24h',
      name: 'Upper @ 24H Fitness',
      exercises: [
        { exerciseId: 'ex_arnold_press',        targetSets: 3, reps: 10, rest: 90 },
        { exerciseId: 'ex_lat_pulldown',        targetSets: 3, reps: 10, rest: 90 },
        { exerciseId: 'ex_seated_cable_row',    targetSets: 3, reps: 10, rest: 90 },
        { exerciseId: 'ex_machine_chest_press', targetSets: 3, reps: 10, rest: 90 },
        { exerciseId: 'ex_barbell_shrugs',      targetSets: 3, reps: 10, rest: 60 },
        { exerciseId: 'ex_chest_fly',           targetSets: 3, reps: 10, rest: 60 },
        { exerciseId: 'ex_tricep_pushdowns',    targetSets: 3, reps: 10, rest: 45 },
        { exerciseId: 'ex_hammer_curl',         targetSets: 3, reps: 10, rest: 45 },
      ],
    },
    {
      id: 'tmpl_lower_24h',
      name: 'Lower @ 24H Fitness',
      exercises: [
        { exerciseId: 'ex_leg_press',          targetSets: 3, reps: 10, rest: 120 },
        { exerciseId: 'ex_leg_extensions',     targetSets: 3, reps: 10, rest: 60 },
        { exerciseId: 'ex_seated_leg_curls',   targetSets: 3, reps: 10, rest: 60 },
        { exerciseId: 'ex_hip_adductions',     targetSets: 3, reps: 10, rest: 60 },
        { exerciseId: 'ex_calf_raise',         targetSets: 3, reps: 15, rest: 45 },
        { exerciseId: 'ex_back_extensions',    targetSets: 3, reps: 10, rest: 60 },
        { exerciseId: 'ex_hanging_leg_raises', targetSets: 3, reps: 10, rest: 45 },
      ],
    },
  ]
}

/** Weekly schedule from the provided plan: Upper / Lower alternating + a bodyweight day. */
export function makeDefaultSchedule() {
  return {
    Monday: 'tmpl_upper_day',
    Tuesday: 'tmpl_lower_day',
    Wednesday: 'tmpl_upper_day',
    Thursday: 'tmpl_lower_day',
    Friday: 'tmpl_bodyweight_day',
    Saturday: null,
    Sunday: null,
  }
}
